<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks and includes.
 */

use Drupal\Core\Routing\RouteMatchInterface;

require_once 'inc/hooks.php';

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function backerymails_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.backerymails':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
